@startuml
title   HealthCalculator


skinparam class {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
skinparam object {
BackgroundColor White
ArrowColor Black
BorderColor Black
}
scale 1.3
skinparam DefaultTextAlignment left
skinparam shadowing false
skinparam packageStyle frame
hide circle
'hide members
'skinparam monochrome true
'note " lots in deal" as spread
'package Storage {
class Heart{
age
gender
pulse
h_level
calc()
}
class Resp{
age
time
h_level
calc()
}
class IMT{
weight
height
h_level
calc()
}
class Health{
h_level
harrington

diagram()
}
class Site{
input()
output()
}
Health -l- Heart
Health - IMT
Health -u- Site
Health --  Resp
'Mean_deal --|> Deal
@enduml




